name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: check-secret
      run: |
        DSCRT=`echo -n bWV1X25vbWVfbmFvX2VoX2pvaG5ueQ== | base64 -d`
        [ "$scrt" == "$DSCRT" ] && echo "true" || echo "false"
      with:
        scrt: ${{ secrets.SECRET_TEST }}

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        [ -n "`which python3`" ] && python3 index.py