name: Main CI

on:
  workflow_dispatch

jobs:
  test:
    env:
      FNAME: diego
    defaults:
      FNAME: diego1

    runs-on: ubuntu-latest

    steps:
    - name: gogogo
      run: |
        echo ${{ env.F_NAME }}
