name: Main CI

on:
  workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    name: A job to say hello

    env:
      F_NAME: diego

    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: ./actions/
        with:
          who-to-greet: 'Mona the Octocat'
          pass_env: ${{ env.F_NAME }}
      - run: |
          echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
